import Head from "next/head";
import AppLayout from "@/components/AppLayout";
import EditAnime from "@/components/EditAnime";
import EditEpisodes from "@/components/EditEpisodes";
import EditOpenings from "@/components/EditOpenings";
import EditEndings from "@/components/EditEndings";
import SiglasList from "@/components/SiglasList";
import Tabs from "@/components/Tabs";
import { useContext } from "react";
import { SiglasContext } from "@/context/SiglasContext";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Edit() {
  const href = useRouter();
  const { siglas } = href.query;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <SiglasList>
          <Tabs isSteeps={siglas ? true : false}>
            <EditAnime label="Anime" />
            <EditEpisodes label="Episodes" />
            <EditOpenings label="openings" />
            <EditEndings label="Endings" />
            <ViewEdit siglas={siglas} label="all" />
          </Tabs>
        </SiglasList>
      </AppLayout>
    </>
  );
}

const ViewEdit = ({ siglas }) => {
  const [siglasPage] = useContext(SiglasContext);

  if (!siglas) {
    return undefined;
  }

  return (
    <ul>
      <Link href={"/edit/" + siglasPage}>Editar</Link>
      <Link href={"/" + siglasPage}>Ver</Link>
    </ul>
  );
};
