import EditAnime from "@/components/EditAnime/EditAnime.jsx";
import Steeps from "@/components/UI/Steeps/Steeps.jsx";
import { useRouter } from "next/router";
import ToolbarEdit from "@/components/UI/ToolBarEdit.jsx";
import styles from "./edit.module.css";
import Head from "next/head";
import AppLayout from "@/components/AppLayout";
import { ThemeProvider } from "@/context/ThemeContext.jsx";
//https://github.com/do-community/building-a-tabs-component-react/blob/master/src/components/Tabs.js
const Edit = () => {
  const href = useRouter();
  const { siglas } = href.query;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
        <AppLayout>
          {typeof siglas !== "undefined" ? <ToolbarEdit /> : <Steeps />}
          <div className={styles.tabcontent}>
            <EditAnime />
          </div>
        </AppLayout>
      </ThemeProvider>
    </>
  );
};
export default Edit;
