import EditAnime from "@/components/EditAnime";
// import Steeps from "@/components/UI/Steeps/index.jsx";
// import ToolbarEdit from "@/components/UI/ToolbarEdit/index.jsx";
import styles from "./edit.module.css";
import Head from "next/head";
import AppLayout from "@/components/AppLayout";
import { ThemeProvider } from "@/context/ThemeContext.jsx";
import EditEpisodes from "@/components/EditEpisodes";
import EditOpenings from "@/components/EditOpenings";
import EditEndings from "@/components/EditEndings";
import { useSiglas } from "../../hooks/useSiglas";

//https://github.com/do-community/building-a-tabs-component-react/blob/master/src/components/Tabs.js
const Edit = () => {
  const [siglas, siglasLista, siglasPage, changeSiglasList] = useSiglas();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
        <AppLayout>
          <div className={styles.tabcontent}>
            <select onChange={(e) => changeSiglasList(e.target.value)}>
              <option value="else">ninguna de ellas</option>
              {siglasLista.map((s, i) => {
                <option key={i} value={s}>
                  {s}
                </option>;
              })}
            </select>
            {!siglas ? (
              // <input
              //   type="text"
              //   className={styles.input}
              //   placeholder="Siglas"
              //   value={siglasPage}
              // />
              <p>Hola</p>
            ) : (
              ""
            )}

            <EditAnime siglas={siglasPage} />
            <EditEpisodes siglas={siglasPage} />
            <EditOpenings siglas={siglasPage} />
            <EditEndings siglas={siglasPage} />
          </div>
        </AppLayout>
      </ThemeProvider>
    </>
  );
};

export default Edit;
